version: '3.5'

services:

  shiptalent_frontend:
    container_name: shiptalent_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/shiptalent_frontend'
      # - '/usr/src/shiptalent_frontend/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development