version: '3.5'

services:

  shiptalent_frontend:
    container_name: shiptalent_frontend
    # environment:
    #   - NODE_ENV=$NODE_ENV
    #   - NODE_PATH = $NODE_PATH
    #   - REACT_APP_API_SERVER = $REACT_APP_API_SERVER
    #   - REACT_APP_API_URL = $REACT_APP_API_URL
    
    build:
      context: .      
      args: 
        NODE_ENV: development
        NODE_PATH: src/
        REACT_APP_API_SERVER: http://192.168.0.121:8000
        REACT_APP_API_URL: http://192.168.0.121:8000/api/v1
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/shiptalent_frontend'
      # - '/usr/src/shiptalent_frontend/node_modules'
    ports:
      - '3000:3000'
