version: 2.1
jobs:
  build:
    docker:
      - image: $DOCKER_REPOSITORY:predefined
        auth:
          username: $MY_DOCKERHUB_USER
          password: $MY_DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $TARGET_SERVER_SSH_FINGERPRINT
      - run:
          name: Deploy app from docker repository to server
          command: |
            ssh -o StrictHostKeyChecking=no $TARGET_SERVER_USER_NAME@$TARGET_SERVER_ADDRESS "/bin/bash $DEPLOYMENT_SCRIPT_FILE_PATH $MY_DOCKERHUB_USER $MY_DOCKERHUB_PASSWORD $DOCKER_REPOSITORY:$DOCKER_REPOSITORY_TAG"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
